[package]
name = "reochat"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
strip = true
lto = true

[dependencies]
chrono = "0.4.24"
iced = { version = "0.8.0", features = ["svg"] }
once_cell = "1.17.1"
